# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JianShuDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'Masonry', '~> 1.0.2'
pod 'HMSegmentedControl', '~> 1.5.4'
pod 'ReactiveCocoa', '~> 2.5'

  target 'JianShuDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JianShuDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
